[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
environment = { path = "../environment" }
errors = { path = "../errors" }
repository = { path = "../repository" }
model = { path = "../model" }

serde_json = "1.0.138"
argon2 = "0.5.0"
chrono = "0.4.39"
base64 = "0.21.0"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
redis = { version = "0.27.4", features = ["tokio-comp"] }
jsonwebtoken = "9.3.0"


